### ISSUE TITLE
Assurance qualité

### ISSUE THREAD

**Issue by t-constantin** [ArcticWalrus/Projet-S4#15]
Préparer les tests pour la démonstration lors de l'audit 1.

**Comment by ArcticWalrus** [comment]
Plan d'assurance qualité ainsi que des critères d'évaluation de l'AQ

**Comment by ArcticWalrus** [comment]
![screenshot from 2019-02-21 13-34-44](https://user-images.githubusercontent.com/32340717/53192892-83fdbe80-35dd-11e9-83cc-23bf60068ed1.png)
