### ISSUE TITLE
Template journal de bord

### ISSUE THREAD

**Issue by t-constantin** [ArcticWalrus/Projet-S4#21]
Créer un template à utiliser par tous pour le journal de bord individuel:
-temps
-tâches travaillées
-bloquants/besoins
-solutions aux bloquants

**Comment by Oli-Dem** [comment]
c'est fait, le [template](https://docs.google.com/spreadsheets/d/16NJAXyxLX9ZtbsAuxv21fD44a44kqqxK8len7pGIkgk/edit#gid=0) est dans le dossier de templates sur le drive.
