### ISSUE TITLE
Investigation heartbeat sensor

### ISSUE THREAD

**Issue by t-constantin** [ArcticWalrus/Projet-S4#26]
Recherche sur le coût du capteur
Signal de sortie
Précision du capteur
Trouver un modèle qu'il serait possible d'acheter
Autre

**Comment by Kitty-kat-lol** [comment]
Après recherche, le capteur vaut 99c.

Fonctionnement: la sortie est un signal analogique qui représente à quelle point le sang dans un doigt empeche la lumiere de passer au travers. Lors d'un battement, il y a plus de sang dans le doigt ce qui provoque un changement de voltage. Le sang revient à la normale entre les battements et le signal redevient (relativement) stable.

Le le cout pour que le campteur arrive dans un delais résonnable serait de 17$ avec la livraison. 

Le concept étant relativement simple une led et un/e photo-résitance/photo-transostor pourrait permettre de fabrique le capteur à cout moindre.

**Comment by ArcticWalrus** [comment]
Met le lien pour le capteur ici!

**Comment by Kitty-kat-lol** [comment]
Trouvé nouveau prix amazon prime delivery pour 12$
(vient avec un oxiometer in it (%d'oxygen dans le sang))
https://www.amazon.ca/Lysignal-MAX30100-Oximeter-Assistant-Monitoring/dp/B073W999X2/ref=sr_1_4?ie=UTF8&qid=1549399516&sr=8-4&keywords=pulse+sensor

**Comment by t-constantin** [comment]
so, on commande ça?

**Comment by Kitty-kat-lol** [comment]
les infos sont ici au besoins mais l'investigation est terminée
