### ISSUE TITLE
Présentation du produit

### ISSUE THREAD

**Issue by Kitty-kat-lol** [ArcticWalrus/Projet-S4#36]
Let's go team 4h i gess

**Comment by Kitty-kat-lol** [comment]
did a first view, not shure of the format it should take but it's in conception for now

**Comment by etibones** [comment]
Kept @Kitty-kat-lol base form, and changed some stuff since I felt some repetitions

**Comment by Kitty-kat-lol** [comment]
Almost finished, the great spiritual guide used his foresight to advise us, we just need to follow his advice in a final version and the souls of the damned shall be saved.

**Comment by Kitty-kat-lol** [comment]
est ce que tout vas bien @t-constantin on te laissait la fin, si tu peut finalement pas c pas grave je vais m'en occuper

**Comment by Kitty-kat-lol** [comment]
srry misclick

**Comment by t-constantin** [comment]
Oui ça va, j'attends simplement vos commentaires et ceux de Tobie

**Comment by t-constantin** [comment]
@Kitty-kat-lol tu répondras aussi à mes questions sur le channel discord
