### ISSUE TITLE
FPGA Logic

### ISSUE THREAD

**Issue by Kitty-kat-lol** [ArcticWalrus/Projet-S4#38]
Programmer une chaine de traitement sur la carte FPGA

**Comment by Kitty-kat-lol** [comment]
Le hdmi sort 5V

**Comment by Kitty-kat-lol** [comment]
Donc on dois faire quoi ici ?

**Comment by tobiedesgreniers** [comment]
tâche closed et sera divisée en d'autres tâches suite à la réunion du 18 mars concernant les choix de conception des chaines de traitement
