### ISSUE TITLE
Commander capteur magnétique

### ISSUE THREAD

**Issue by t-constantin** [ArcticWalrus/Projet-S4#4]
Commander le capteur pour la vitesse

**Comment by ArcticWalrus** [comment]
Malgré le fait qu'on ne planifie pas l'utiliser, est-ce qu'on pourrait regarder pour un capteur de rythme cardiac si jamais on finit par faire cette fonctionnalité?

**Comment by t-constantin** [comment]
Ouais je suis d'accord!

**Comment by tobiedesgreniers** [comment]
Oui bonne idée!
Donc au final, nous avons 3 capteurs je crois
L'accéléromètre, le capteur magnétique de vitesse, et le capteur de rythme cardiaque?
Il faudrait commander le capteur magnétique de vitesse et seulement s'informer pour celui de rythme cardiaque?
